### ISSUE TITLE
Support for parsing `[content](link)`

### ISSUE THREAD

**Issue by tommyjiang** [wzpan/hexo-tag-bootstrap#11]
Hope to replace `text` as  `[content](link)` and realize the following function:

```
{% label [content](link) default %}
```

convert to:

```
<span class="label label-default"><a href="link" target="_blank">content</a></span>
```

**Comment by noraj** [comment]
@tommyjiang Can you translate what do you mean in english please?
Translators are not very accurate.

**Comment by wzpan** [comment]
Hmm. I guess he wants to support hyperlink in all the tags.

**Comment by tommyjiang** [comment]
Yeah, that's true. I just use `label` as an example.

**Comment by wzpan** [comment]
@tommyjiang I will release a new version to support this request soon. Actually I have accomplished this feature in my own blog.

**Comment by wzpan** [comment]
@tommyjiang try upgrade to 0.2.1 and it should works.

``` javascript
{% label [content](link) default %}
```

**Comment by tommyjiang** [comment]
@wzpan Thank you.
