### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by noraj** [wzpan/hexo-tag-bootstrap#13]
Can you provide a changelog either in `CHANGELOG.md` or make release on github https://github.com/wzpan/hexo-tag-bootstrap/releases

**Comment by noraj** [comment]
0.1.2 -> 0.2.0 seems there are breaking changes
https://gitlab.com/rawsec/Rawsec-website/merge_requests/70/diffs

Without changelog to alert of the breaking change and to say what to do it's pretty hard to upgrade.
https://gitlab.com/rawsec/Rawsec-website/-/jobs/339872262
https://gitlab.com/rawsec/Rawsec-website/-/jobs/339874128

**Comment by wzpan** [comment]
Good advice. Later I will create one.

**Comment by wzpan** [comment]
@noraj please refer to the release page: https://github.com/wzpan/hexo-tag-bootstrap/releases .

**Comment by noraj** [comment]
This is minimalist but better than nothing :)

One has to enlarge with the 3 dots button to see the comment.

![image](https://user-images.githubusercontent.com/16578570/68593560-098c0c00-0496-11ea-8e8a-a11a0e066d0c.png)

I think those are only the git commit comments from the tags. But you can draft release on github to add arbitrary comments not stored in git.

Example:
![image](https://user-images.githubusercontent.com/16578570/68593687-4d7f1100-0496-11ea-9928-4042636824ba.png)

**Comment by noraj** [comment]
I have a breaking change in my project introduced by `0.1.2 -> 0.2.0` but can't spot where does it come from and the CHANGELOG is way to minimalist to give me a clue.
Please can you publish a full changelog.

**Comment by wzpan** [comment]
Can you try upgrading bootstrap?

**Comment by noraj** [comment]
This would mean update https://gist.github.com/noraj/378b7aa01cc4f4c079120e6c2e2e3593 which is a lot of work and not really viable. Let's consider your plugin work only for bootstrap based themes.
