### ISSUE TITLE
bootstrap minimal CSS

### ISSUE THREAD

**Issue by noraj** [wzpan/hexo-tag-bootstrap#3]
Hello,

I made minimal CSS (generated from boostrap) just for label, button, glyphicons, badges and alert so we have just to add it in a theme css to make the design work.

Can you add it in your repo to able users to have a working css with the plugin ?

Thanks

**Comment by wzpan** [comment]
Hi @shark-oxi ,

Sorry for missing this issue.

I can't come up with a proper way to add such css to a hexo plugin. Can you give an idea?

**Comment by noraj** [comment]
It seems to me impossible that hexo-tag-bootstrap can handle all tiers-theme so the simpliest way may be just to add a css file to your repo and say in the README to add it manualy to the css theme code.

[The css](http://hastebin.com/fucikehati.css)

It's far to be perfect of minimalist, I think it need to be improved.

What do you think about it ?

**Comment by wzpan** [comment]
I've modified the readme and add a section to give such tips to non bootstrap-based theme. Thanks.

**Comment by noraj** [comment]
Thanks too.
I don't know the retention time of the link I give you so feel free to copy it somewhere else.

**Comment by wzpan** [comment]
Don't worry. I've transferred the CSS file to gist: https://gist.github.com/wzpan/ad05a8bb162fbc560259
