### ISSUE TITLE
写在 {% alert warning %}...{% endalert %} 之后的 4级标题解析失效

### ISSUE THREAD

**Issue by JoySR** [wzpan/hexo-tag-bootstrap#4]
```
{% alert warning %}内容{% endalert %}

#### 标题

另一行内容
```

按照上面的格式写完文章后，解析出来的 warning 部分正常，但是下面的 `#### 标题` 会原样输出，而且输出的结果是 `#### 标题 另一行内容`，也就是和后面的内容合到一起了。去掉 `{% alert warning %}内容{% endalert %}` 后标题就解析正常了。

**Comment by wzpan** [comment]
Hi @Joysr ，try to write alert plugin in multiple lines _e.g._

```
{% alert warning %}
contents
{% endalert %}
```

rather than in one line. That probably helps.

**Comment by JoySR** [comment]
Hi, thanks for your reply.
It works well, problem solved. :)
Have a nice week.
