### ISSUE TITLE
Title not rendered after a label tag

### ISSUE THREAD

**Issue by ghost** [wzpan/hexo-tag-bootstrap#5]
Hi,

Thanks for this plugin, it's quite good!

However, I've encountered a little bug. I've got this sample text:

```
{% label Info info %} This is an information preceded by a label

## Some title
```

The title is not rendered at all.

When the label is not on the same line than the text, the title is correctly rendered:

```
{% label Info info %}
This is an information preceded by a label

## Some title
```

 A workaround I've found is to add a html comment between:

```
{% label Info info %} This is an information preceded by a label
<!-- -->
## Some title
```

It's a workaround: it works, but it should not be necessary ;)

**Comment by wzpan** [comment]
Hi @Arcesilas ,

It's a known bug when using hexo-tag-bootstrap in Hexo 3.x , while it works perfectly user Hexo 2.x.

A prefer way for now is to write it in multiple lines, like you said.
