### ISSUE TITLE
怎么使其他主题也支持此扩展标签？

### ISSUE THREAD

**Issue by ghost** [wzpan/hexo-tag-bootstrap#6]
>If you're using a Hexo theme that is not built on Twitter Bootstrap, you can have a try at a minimal CSS provided by @shark-oxi which wraps all the neccessary stylesheets for the above plugins.

我下载了 css 文件，但检索良久也未发现如何正确地在其他主题中使用。将其转换为 styl 格式引用，有如下报错信息。

```
ERROR Asset render failed: css/main.css
TypeError: /～～～～/source/css/_custom/bootstrap.styl:1138:28
   1134| .btn[disabled],
   1135| fieldset[disabled] .btn
   1136|     cursor not-allowed
   1137|     opacity 0.65
   1138|     filter alpha(opacity=65)
------------------------------------^
   1139|     -webkit-box-shadow none
   1140|     box-shadow none
   1141| 
```

**Comment by wzpan** [comment]
为什么要把它转成styl？直接使用.css文件就可以了呀。

**Comment by ghost** [comment]
@wzpan 比如 NexT 主题，CSS 文件夹中是 styl 格式的文件，所以我也转了。我也试过直接把 .css 文件放在 CSS 文件夹中，但是没有效果。

**Comment by wzpan** [comment]
由于这个插件主要针对 bootstrap-based 主题，所以并不会考虑其他前端框架主题的兼容。
而这个 minimal bootstrap 是 @noraj1337  提供的（见 #3 ）。建议找他咨询。
